describe('Bank Demo Tests', function(){
    
    // beforeEach(function()
    // {
    //     cy.visit('https://www.demo.bnz.co.nz/client/', {headers: {"Accept-Encoding": "gzip, deflate"}})
    // })

    it('Verify you can navigate to Payees page using the navigation menu', function(){
        cy.visit('https://www.demo.bnz.co.nz/client/', {headers: {"Accept-Encoding": "gzip, deflate"}})
        cy.get('button').contains('Menu').click()
        cy.get('span').contains('Payees').click()
    })

    it('Verify you can add new payee in the Payees page', function(){
        cy.visit('https://www.demo.bnz.co.nz/client/', {headers: {"Accept-Encoding": "gzip, deflate"}})
        cy.get('button').contains('Menu').click()
        cy.get('span').contains('Payees').click()
        cy.get('button').contains('Add').click()
        cy.get('#ComboboxInput-apm-name').type('Test User')
        cy.get('#ComboboxList-apm-name > :nth-child(2)').click()
        cy.get('#apm-bank').type('12')
        cy.get('#apm-branch').type('3456')
        cy.get('#apm-account').type('7890123')
        cy.get('#apm-suffix').type('001')
        cy.get('.js-submit').click()
        // exact location
        cy.get(':nth-child(5) > .PaddedItem span.js-payee-name').should('contain.text', 'Test User')
        cy.get(':nth-child(5) > .PaddedItem p.js-payee-account').should('contain.text', '12-3456-7890123-001')
        // general search
        // cy.get('.PaddedItem span.js-payee-name').should('contain.text', 'Test User')
        // cy.get('.PaddedItem p.js-payee-account').should('contain.text', '12-3456-7890123-001')
    })

    it('Verify payee name is a required field', function(){
        cy.visit('https://www.demo.bnz.co.nz/client/', {headers: {"Accept-Encoding": "gzip, deflate"}})
        cy.get('button').contains('Menu').click()
        cy.get('span').contains('Payees').click()
        cy.get('button').contains('Add').click()
        cy.get('.js-submit').click()
        cy.get('.tooltip-panel > .text').should('have.text', 'Payee Name is a required field. Please complete to continue.')
        cy.get('#ComboboxInput-apm-name').type('Test User')
        cy.get('#ComboboxList-apm-name > :nth-child(2)').click()
        cy.get('.js-submit').click()
        cy.get('.error-header').should('have.text', '4 problems found. Please correct the fields highlighted below.')
        cy.get('#apm-bank').click()
        cy.get('.tooltip-panel > .text').should('have.text', 'Bank Code is a required field. Please complete to continue.')
        cy.get('#apm-branch').click()
        cy.get('.tooltip-panel > .text').should('have.text', 'Branch Code is a required field. Please complete to continue.')
        cy.get('#apm-account').click()
        cy.get('.tooltip-panel > .text').should('have.text', 'Account Number is a required field. Please complete to continue.')
        cy.get('#apm-suffix').click()
        cy.get('.tooltip-panel > .text').should('have.text', 'Suffix is a required field. Please complete to continue.')
        cy.get('#apm-this-particulars').click()
        cy.get('#apm-bank').type('12')
        cy.get('#apm-branch').type('3456')
        cy.get('#apm-account').type('7890123')
        cy.get('#apm-suffix').type('001')
        cy.get('.error-header').should('not.exist')
    })

    it('Verify that payees can be sorted by name', function(){
        cy.visit('https://www.demo.bnz.co.nz/client/', {headers: {"Accept-Encoding": "gzip, deflate"}})
        cy.get('button').contains('Menu').click()
        cy.get('span').contains('Payees').click()
        cy.get('button').contains('Add').click()
        cy.get('#ComboboxInput-apm-name').type('Test User')
        cy.get('#ComboboxList-apm-name > :nth-child(2)').click()
        cy.get('#apm-bank').type('12')
        cy.get('#apm-branch').type('3456')
        cy.get('#apm-account').type('7890123')
        cy.get('#apm-suffix').type('001')
        cy.get('.js-submit').click()
        cy.get('.PaddedItem span.js-payee-name').should('contain.text', 'Test User')
        cy.get('ul .PaddedItem span.js-payee-name').invoke('text').should('eq', ['Auckland Council', 'Babysitter', 'Cleaners', 'MERIDIAN ENERGY', 'Test User','VODAFONE NZ LTD (MOBILE)'].join(''))
        cy.get('.js-payee-name-column > .Language__container').click()
        cy.get('ul .PaddedItem span.js-payee-name').invoke('text').should('eq', ['VODAFONE NZ LTD (MOBILE)', 'Test User', 'MERIDIAN ENERGY', 'Cleaners', 'Babysitter', 'Auckland Council'].join(''))
    })

    it('Navigate to Payments page', function(){
        cy.visit('https://www.demo.bnz.co.nz/client/', {headers: {"Accept-Encoding": "gzip, deflate"}})
        cy.get('.js-main-menu-btn > .Icons').click()
        cy.get('.js-main-menu-paytransfer > .Button').click()
        cy.get('[data-testid="from-account-chooser"]').click()
        cy.get('p').contains('Everyday').click()
        cy.get('[data-testid="to-account-chooser"]').click()
        cy.get('[data-testid="to-account-accounts-tab"]').click()
        cy.get('p').contains('Bills').click()
        cy.get('#field-bnz-web-ui-toolkit-9').type('500')
        cy.get('button').contains('Transfer').click()
        cy.get('#account-ACC-1 > .account-info > .account-balance').should('have.text', '2,000.00')
        cy.get('span.message').should('have.text','Transfer successful')
    })

})